### ISSUE TITLE
Spécification du connecteur du Raspberry (GPIO)

### ISSUE THREAD

**Issue by jean-michel-gonet** [mic-inf-2017/raspberry-pi-psu.X#2]
# Pourquoi
- Parce que le module PSU se connecte dessus.

# Condition de satisfaction
- Connaître tous les connecteurs du Raspberry.

**Comment by Ritier** [comment]
http://www.conrad.ch/ce/fr/product/1182195/Cable-de-raccordement-Raspberry-Pi-Joy-it-RB-CB4-050-multicolore-1-pcs/?ref=detview1&rt=detview1&rb=1

**Comment by Ennakouch** [comment]
[Uploading GPIO.docx…]()

**Comment by jean-michel-gonet** [comment]
- Alimentation: 2, 4
- I2C - SDA: 3
- I2C - SCL: 5
- Masse: 6, 14, 20, 30, 34; 9, 25, 39
