### ISSUE TITLE
Spécification d'un LiPo 2s

### ISSUE THREAD

**Issue by jean-michel-gonet** [mic-inf-2017/raspberry-pi-psu.X#4]
# Pourquoi?
- Pour savoir comment il marche.

# Condition de satisfaction
- Tension maximum.
- Tension minimum
- Quelle marge laisser?

**Comment by Roubatel** [comment]
Batteries LiPo 2S

2 cellules de 3,7V en série, 7,4V en sortie

Tension minimale pour la batterie : 6V

Marge de sécurité pour la batterie : 6,4V

Tension max : 8,4V
 
http://www.rcaces.org/RC%20Aces%20News%20Letter/A_Guide_to_LiPo_Batteries.pdf
